project:
  type: book

book:
  title: "Hands-On Machine Learning with R, 2ed"
  author: "Brad Boehmke & Brandon Greenwell"
  date: today
  search: true
  repo-url: https://github.com/koalaverse/homlr-2ed
  repo-branch: main
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  favicon: figures/homl-cover.jpg
  cover-image: figures/homl-cover.jpg
  sharing: [twitter]

  chapters:
    - index.qmd
    - preface-2e.qmd
    - 01-intro.qmd
    - part: "Supervised Learning"
      chapters:
        - 02-modeling-process.qmd
        - 03-slr.qmd
        - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - homl.scss
    code-link: true
    callout-appearance: simple
  pdf:
    documentclass: scrreprt
