project:
  type: book

book:
  title: "Hands-On Machine Learning with R, 2ed"
  author: "Brad Boehmke & Brandon Greenwell"
  date: today
  search: true
  repo-url: https://github.com/koalaverse/homlr-2ed
  repo-branch: main
  repo-actions: [edit, issue]
  favicon: homl-cover.jpg
  cover-image: homl-cover.jpg
  sharing: [twitter]

  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    callout-appearance: simple
  pdf:
    documentclass: scrreprt



