on:
  push:
    branches: main
  pull_request:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:
  schedule:
    # run every day at 11 PM
    - cron: '0 23 * * *'

name: Render and publish book

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install webshot dependency
        run: webshot::install_phantomjs()
        shell: Rscript {0}

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
